language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
before_script:
  - nvm install 4
  - nvm use 4
  - npm i -g gulp
  - npm i
  - touch tests.db
  - chmod a+w tests.db
script:
  - ./src/api/vendor/phpunit/phpunit/phpunit -c test/api/phpunit.xml
  - gulp test-app

