language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
before_script:
  - nvm install 4
  - nvm use 4
  - npm i -g gulp
  - npm i
  - touch tests.db
  - chmod a+w tests.db
script:
  - ./src/api/vendor/phpunit/phpunit/phpunit -c test/api/phpunit.xml
  - gulp coverage
after_success:
  - echo -e "<?php\n  print phpversion();" > version.php
  - curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox_uploader.sh
  - chmod +x dropbox_uploader.sh
  - ./dropbox_uploader.sh -f /dev/null upload api-coverage/ coverage-$(php version.php)/
  - ./dropbox_uploader.sh -f /dev/null upload coverage.html coverage-$(php version.php)/

